### ISSUE TITLE
Seems to be an issue with sppmon.py

### ISSUE THREAD

**Issue by silverstringit** [IBM/spectrum-protect-sppmon#31]
Hi, sorry I'm new to github so this may be in wrong place.

I have tried to install SPPMON following your guides but have run into an issue where very little data is being pulled into Grafana.

I'm trying to install as a container, and have followed all the steps.

**if I manually try and run some of the jobs i get the following**

/usr/local/bin/python3.8 /home/sppmon/spectrum-protect-sppmon/python/sppmon.py --/home/sppmon/spectrum-protect-sppmon/python/sppmon.conf --daily
Traceback (most recent call last):
  File "/home/sppmon/spectrum-protect-sppmon/python/sppmon.py", line 58, in <module>
    from influx.influx_client import InfluxClient
  File "/home/sppmon/spectrum-protect-sppmon/python/influx/influx_client.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

*sppmon.py*
the issue in line 58 seems to be this
from influx.influx_client import InfluxClient

and in influx_client.py", line 11
import requests

i have also checked to see what is going on in var/lo/messages and can see the following 
 
ec 23 13:48:48 sppmon journal: t=2020-12-23T13:48:48+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=17 name="VADP CPU & RAM Health alert" changing state to=no_data
Dec 23 13:48:54 sppmon journal: ts=2020-12-23T13:48:54.671427Z lvl=info msg="Executing query" log_id=0RFvwTHW000 service=query query="SELECT difference(errorCount) FROM sppmon.rp_days_14.sppmon_metrics WHERE constant = 'True' AND time > now() - 1d"
Dec 23 13:48:54 sppmon journal: [httpd] 172.17.0.1 - grafanaReader [23/Dec/2020:13:48:54 +0000] "GET /query?db=sppmon&epoch=s&q=SELECT+difference%28%22errorCount%22%29+FROM+%22sppmon_metrics%22+WHERE+%22constant%22+%3D+%27True%27+AND+time+%3E+now%28%29+-+24h HTTP/1.1" 200 57 "-" "Grafana" 98ed0b7d-4525-11eb-883b-0242ac110002 958
Dec 23 13:48:54 sppmon journal: ts=2020-12-23T13:48:54.673667Z lvl=info msg="Executing query" log_id=0RFvwTHW000 service=query query="SELECT difference(errorCount) FROM sppmon.rp_days_14.sppmon_metrics WHERE daily = 'True' AND time > now() - 1d"
Dec 23 13:48:54 sppmon journal: [httpd] 172.17.0.1 - grafanaReader [23/Dec/2020:13:48:54 +0000] "GET /query?db=sppmon&epoch=s&q=SELECT+difference%28%22errorCount%22%29+FROM+%22sppmon_metrics%22+WHERE+%22daily%22+%3D+%27True%27+AND+time+%3E+now%28%29+-+24h HTTP/1.1" 200 57 "-" "Grafana" 98ed683f-4525-11eb-883c-0242ac110002 594
Dec 23 13:48:54 sppmon journal: ts=2020-12-23T13:48:54.676162Z lvl=info msg="Executing query" log_id=0RFvwTHW000 service=query query="SELECT difference(errorCount) FROM sppmon.rp_days_14.sppmon_metrics WHERE \"all\" = 'True' AND time > now() - 1d"
Dec 23 13:48:54 sppmon journal: [httpd] 172.17.0.1 - grafanaReader [23/Dec/2020:13:48:54 +0000] "GET /query?db=sppmon&epoch=s&q=SELECT+difference%28%22errorCount%22%29+FROM+%22sppmon_metrics%22+WHERE+%22all%22+%3D+%27True%27+AND+time+%3E+now%28%29+-+24h HTTP/1.1" 200 57 "-" "Grafana" 98edac2a-4525-11eb-883d-0242ac110002 1521
Dec 23 13:48:54 sppmon journal: ts=2020-12-23T13:48:54.682778Z lvl=info msg="Executing query" log_id=0RFvwTHW000 service=query query="SELECT difference(errorCount) FROM sppmon.rp_days_14.sppmon_metrics WHERE hourly = 'True' AND time > now() - 1d"
Dec 23 13:48:54 sppmon journal: [httpd] 172.17.0.1 - grafanaReader [23/Dec/2020:13:48:54 +0000] "GET /query?db=sppmon&epoch=s&q=SELECT+difference%28%22errorCount%22%29+FROM+%22sppmon_metrics%22+WHERE+%22hourly%22+%3D+%27True%27+AND+time+%3E+now%28%29+-+24h HTTP/1.1" 200 57 "-" "Grafana" 98eec625-4525-11eb-883e-0242ac110002 743
Dec 23 13:48:54 sppmon journal: ts=2020-12-23T13:48:54.684735Z lvl=info msg="Executing query" log_id=0RFvwTHW000 service=query query="SELECT difference(errorCount) FROM sppmon.rp_days_14.sppmon_metrics WHERE (constant != 'True' AND \"all\" != 'True' AND daily != 'True' AND hourly != 'True') AND time > now() - 1d"
Dec 23 13:48:54 sppmon journal: [httpd] 172.17.0.1 - grafanaReader [23/Dec/2020:13:48:54 +0000] "GET /query?db=sppmon&epoch=s&q=SELECT+difference%28%22errorCount%22%29+FROM+%22sppmon_metrics%22+WHERE+%28%22constant%22+%21%3D+%27True%27+AND+%22all%22+%21%3D+%27True%27+AND+%22daily%22+%21%3D+%27True%27+AND+%22hourly%22+%21%3D+%27True%27%29+AND+time+%3E+now%28%29+-+24h HTTP/1.1" 200 175 "-" "Grafana" 98ef17c6-4525-11eb-883f-0242ac110002 872
Dec 23 13:48:54 sppmon journal: t=2020-12-23T13:48:54+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=19 name="SPPmon Collection Errors delta alert" changing state to=keep_state

so it seems to grab some data, but not all! so majority of the dashboards have nothing on them.

if someone would be able to give me a hand getting it working id be greatly appreciative

many thanks

AJ

**Comment by silverstringit** [comment]
![sppmon](https://user-images.githubusercontent.com/60353151/103008303-d3400d80-452c-11eb-93fb-00fcbd026011.JPG)

**Comment by NielsKorschinsky** [comment]
Hello @silverstringit 
This is the right place to ask such a question.

For me it seems like not all of the required python modules are installed (`requests`).
Please check again the install instruction and re-build the container - the dockerfile should install all requirements.
If the problem perexists please comment again and I will try to help you out.

As long as SPPMon.py isnt running correctly, grafana can't display any data. This issue should be solved once the script starts running - Grafana seems to work fine.

**Comment by NielsKorschinsky** [comment]
Please try to run SPPMon with following command:
`docker run --rm sppmon`.
If you get the "how to use sppmon"-text everything should work correctly. You were maybe starting sppmon outside of the container, therefore not all requirements were fulfilled. 

You may run sppmon within the container with a command similar to this one:
`docker run --rm -v /home/sppmon/sppmon.conf:/usr/src/app/sppmon.conf:ro,Z -v /home/sppmon/sppmonLogs:/root/sppmonLogs:Z sppmon python sppmon.py --cfg=sppmon.conf --sites`

**Comment by silverstringit** [comment]
cheers for getting back to me.

Ive rebuilt everything from scratch and still appear to be getting issues.

if i run sppmon@sppmon-ubuntu:~$ docker run --rm sppmon .
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: ".": executable file not found in $PATH: unknown.

Yet i can run docker hello-world and the Grafana and influxDB containers fine so im at a bit of a loss why.

I get the same issue on both centos 7.8 and Ubuntu. not sure where the fault lies as im quite new to containers

sppmon@sppmon-ubuntu:~$ docker image ls
REPOSITORY        TAG       IMAGE ID       CREATED          SIZE
sppmon            latest    afb9baddb4ea   25 minutes ago   913MB
python            3.8       f5041c8ae6b1   8 days ago       884MB
influxdb          latest    09375fea906e   13 days ago      307MB
grafana/grafana   latest    3c7f99671289   2 weeks ago      187MB
hello-world       latest    bf756fb1ae65   12 months ago    13.3kB
sppmon@sppmon-ubuntu:~$


so pretty confused

**Comment by silverstringit** [comment]
am also seeing this still if i try and run manually

# query CPU and RAM utilization every 3 minutes
*/3 * * * * /usr/bin/python3.8 /home/sppmon/spectrum-protect-sppmon-master/python/sppmon.py --cfg=/home/sppmon/sppserver1.conf --constant  >/dev/null 2>&1
sppmon@sppmon-ubuntu:~/spectrum-protect-sppmon-master/python$  /usr/bin/python3.8 /home/sppmon/spectrum-protect-sppmon-master/python/sppmon.py --cfg=/home/sppmon/sppserver1.conf --constant
Traceback (most recent call last):
  File "/home/sppmon/spectrum-protect-sppmon-master/python/sppmon.py", line 58, in <module>
    from influx.influx_client import InfluxClient
  File "/home/sppmon/spectrum-protect-sppmon-master/python/influx/influx_client.py", line 12, in <module>
    from influxdb import InfluxDBClient
ModuleNotFoundError: No module named 'influxdb'
sppmon@sppmon-ubuntu:~/spectrum-protect-sppmon-master/python$

**Comment by NielsKorschinsky** [comment]
This seems like a docker-related issue. Do you use WSL under Windows?
I have no real clue what exactly the issue is, probably something with the docker startup or SPPMon not beeing on the $PATH.
Due the wrong setup not all imports are working, therefore are not all dependencies resolved. 

May try to google for the error and find a similar issue with this error code, or maybe @baslerj can help you out here?

**Comment by baslerj** [comment]
@silverstringit sorry that it has taken me a while to get back to this.  I have gone through the containerized SPPMON setup procedure again.  I noted one problem where the instructions are missing steps to open firewall ports for Influxdb and Grafana, and I have updated the instructions to include the required firewall steps.  This does not appear to be the issue you have reported, but it will cause other problems with later steps.
Note that the command you ran recently to the SPPMON container had an extra '.' at the end which caused the `process caused the exec: ".": executable file not found in $PATH: unknown` error.  This command without the extra '.' should work fine.

`docker run --rm sppmon`

**Comment by NielsKorschinsky** [comment]
Please feel free to reopen if the isse still exists or to open a new issue if the topic changed.
